MadMicro.Web/Controllers/AuthController.cs
using MadMicro.Web.Models;
using MadMicro.Web.Services.IService;
using MadMicro.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MadMicro.Web.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ITokenProvider _tokenProvider;
    public AuthController(IAuthService authService, ITokenProvider tokenProvider)
    {
        _authService = authService;
        _tokenProvider = tokenProvider;
    }

    [HttpGet]
    public IActionResult Login()
    {
        UserLoginDTO userLoginDTO = new();
        return View(userLoginDTO);
    }


    [HttpPost]
    public async Task<IActionResult> Login(UserLoginDTO obj)
    {
        ResponseDTO responseDto = await _authService.LoginAsync(obj);

        if (responseDto != null && responseDto.IsSuccess)
        {
            LoginResponseDto loginResponseDto =
               JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result));

            await SignInUser(loginResponseDto);
            _tokenProvider.SetToken(loginResponseDto.Token);
            return RedirectToAction("Index", "Home");
        }
        TempData["error"] = responseDto?.Message;

        return View(obj);
    }

    [HttpGet]
    public IActionResult Register()
    {
        var role = new List<SelectListItem>()
        {
          new SelectListItem{Text=StaticDetail.RoleAdmin, Value=StaticDetail.RoleAdmin},
          new SelectListItem{Text=StaticDetail.RoleCustomer, Value=StaticDetail.RoleCustomer},
        };

        ViewBag.RoleList = role;
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Register(UserRegisterDTO obj)
    {
        ResponseDTO result = await _authService.RegisterAsync(obj);
        ResponseDTO assignRole;

        if (result != null && result.IsSuccess)
        {
            if (string.IsNullOrEmpty(obj.Role))
                obj.Role = StaticDetail.RoleCustomer;

            assignRole = await _authService.AssignRoleLoginAsync(obj);

            if (assignRole != null && assignRole.IsSuccess)
            {
                TempData["success"] = "Registration Successful";
                return RedirectToAction(nameof(Login));
            }
        }

        TempData["error"] = result?.Message;

        var role = new List<SelectListItem>()
        {
          new SelectListItem{Text=StaticDetail.RoleAdmin, Value=StaticDetail.RoleAdmin},
          new SelectListItem{Text=StaticDetail.RoleCustomer, Value=StaticDetail.RoleCustomer},
        };


        ViewBag.RoleList = role;
        return View(obj);
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();
        return RedirectToAction("index", "Home");
    }

    private async Task SignInUser(LoginResponseDto model)
    {
        var handler = new JwtSecurityTokenHandler();

        var jwt = handler.ReadJwtToken(model.Token);

        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
              jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
              jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
              jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));

        identity.AddClaim(new Claim(ClaimTypes.Name,
             jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(ClaimTypes.Role,
             jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));


        var principal = new ClaimsPrincipal(identity);

        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

    }
}

MadMicro.Web/Controllers/CouponController.cs
using MadMicro.Web.Models;
using MadMicro.Web.Services.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MadMicro.Web.Controllers
{
	public class CouponController : Controller
	{
		private readonly ICouponService _couponService;

		public CouponController(ICouponService couponService)
		{
			_couponService = couponService;
		}
		public async Task<IActionResult> CouponIndex()
		{
			List<CouponDTO>? listOfCoupon = new();

			ResponseDTO? response = await _couponService.GetAllCouponAsync();

			if (response != null && response.IsSuccess)
				listOfCoupon = JsonConvert.DeserializeObject<List<CouponDTO>>(response?.Result.ToString());

			if (!string.IsNullOrEmpty(response?.Message))
				TempData["error"] = response?.Message;
			return View(listOfCoupon);
		}

		public async Task<IActionResult> CouponCreate()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CouponCreate(CouponDTO model)
		{
			if (ModelState.IsValid)
			{
				ResponseDTO? response = await _couponService.CreateCouponAsync(model);

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Coupon Created Successful !";
					return RedirectToAction(nameof(CouponIndex));
				}
				TempData["error"] = response?.Message;
			}
			return View(model);
		}

		public async Task<IActionResult> CouponDelete(int couponID)
		{

			ResponseDTO? response = await _couponService.GetCouponByIdAsync(couponID);

			if (response != null && response.IsSuccess)
			{

				var model = JsonConvert.DeserializeObject<CouponDTO>(response.Result.ToString());
				return View(model);

			}
			TempData["error"] = response?.Message;
			return NotFound();
		}

		[HttpPost]
		public async Task<IActionResult> CouponDelete(CouponDTO couponDTO)
		{

			ResponseDTO? response = await _couponService.DeleteCouponAsync(couponDTO.CouponId);

			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "Coupon Deleted Successful !";
				return RedirectToAction(nameof(CouponIndex));
			}
			TempData["error"] = response?.Message;
			return View(couponDTO);
		}

	}
}

MadMicro.Web/Controllers/OrderController.cs
using IdentityModel;
using MadMicro.Web.Models;
using MadMicro.Web.Services.IService;
using MadMicro.Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;

namespace MadMicro.Web.Controllers
{
    public class OrderController : Controller
    {

        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService) =>  _orderService = orderService;

        [Authorize]
        public IActionResult OrderIndex() => View();


        [Authorize]
        public async Task<IActionResult> OrderDetail(int orderId)
        {

            var orderHeaderDto = new OrderHeaderDTO();

            string userId = User.Claims.FirstOrDefault(u => u.Type is JwtRegisteredClaimNames.Sub).Value;

            var res = await _orderService.GetOrder(orderId);

            if (res is not null && res.IsSuccess)
                orderHeaderDto = JsonConvert.DeserializeObject<OrderHeaderDTO>(res.Result!.ToString()!);

            if(!User.IsInRole(StaticDetail.RoleAdmin) && userId != orderHeaderDto.UserId)
                return NotFound();

            return View(orderHeaderDto);
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(string status) 
        {
            IEnumerable<OrderHeaderDTO> orderHeaderList;

            string userId = string.Empty;

          
            userId = User.Claims.FirstOrDefault(u => u.Type is JwtRegisteredClaimNames.Sub).Value;
            

            var res = await _orderService.GetOrders(userId);


            orderHeaderList = (res != null && res.IsSuccess) ? orderHeaderList = 
                orderHeaderList = JsonConvert.DeserializeObject<List<OrderHeaderDTO>>(res.Result!.ToString()!)! : new List<OrderHeaderDTO>();

            switch (status)
            {
                case StaticDetail.Status_Approved:
                    orderHeaderList = orderHeaderList.Where(u => u.Status is StaticDetail.Status_Approved);
                    break;
                case StaticDetail.Status_ReadyToPickup:
                      orderHeaderList = orderHeaderList.Where(u => u.Status is StaticDetail.Status_ReadyToPickup);
                    break;
                case StaticDetail.Status_Cancelled:
                    orderHeaderList = orderHeaderList.Where(u => u.Status is StaticDetail.Status_Cancelled);
                    break;

                default:
                    break;
            }

            return  Json(new { data = orderHeaderList });
        
        }

        [HttpPost("OrderReadyForPickup")]
        public async Task<IActionResult> OrderReadyForPickup(int orderId)
        {
            var res = await _orderService.UpdateOrderStatus(orderId, StaticDetail.Status_ReadyToPickup);
            if (res is null && !res.IsSuccess) return View();

            
            TempData["success"] = "Status Updated Successful";
            return RedirectToAction(nameof(OrderDetail), new { orderId });
        } 
        
        [HttpPost("CompleteOrder")]
        public async Task<IActionResult> CompleteOrder(int orderId)
        {
            var res = await _orderService.UpdateOrderStatus(orderId, StaticDetail.Status_Completed);
            if (res is null && !res.IsSuccess) return View();

            
            TempData["success"] = "Status Updated Successful";
            return RedirectToAction(nameof(OrderDetail), new { orderId });
        }


        [HttpPost("CancelOrder")]
        public async Task<IActionResult> CancelOrder(int orderId)
        {
            var res = await _orderService.UpdateOrderStatus(orderId, StaticDetail.Status_Cancelled);
            if (res is null && !res.IsSuccess) return View();


            TempData["success"] = "Status Updated Successful";
            return RedirectToAction(nameof(OrderDetail), new { orderId });
        }

    }
}

MadMicro.Web/Controllers/ProductController.cs
using MadMicro.Web.Models;
using MadMicro.Web.Services.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MadMicro.Web.Controllers;

public class ProductController : Controller
{
	private readonly IProductService _productService;

	public ProductController(IProductService productService)
	{
		_productService = productService;
	}

	public async Task<IActionResult> ProductIndex()
	{
		List<ProductDTO> listOfProduct = new();
		ResponseDTO? response = await _productService.GetAllProductsAsync();

		if (response != null && response.IsSuccess)
			listOfProduct = JsonConvert.DeserializeObject<List<ProductDTO>>(response.Result.ToString());

		if (!string.IsNullOrEmpty(response?.Message))
			TempData["error"] = response?.Message;

		return View(listOfProduct);
	}

	public async Task<IActionResult> ProductCreate()
	{
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> ProductCreate(ProductDTO productDTO)
	{
		if (ModelState.IsValid)
		{
			ResponseDTO response = await _productService.CreateProductAsync(productDTO);
			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "Product Created Successful";
				return RedirectToAction(nameof(ProductIndex));
			}
			TempData["error"] = response?.Message;
		}
		return View(productDTO);
	}



	public async Task<IActionResult> ProductDelete(int productId)
	{
		ResponseDTO response = await _productService.GetAllProductsByIdAsync(productId);
		if (response != null && response.IsSuccess)
		{
			var model = JsonConvert.DeserializeObject<ProductDTO>(response.Result.ToString());
			return View(model);
		}
		TempData["error"] = response?.Message;
		return NotFound();
	}



	[HttpPost]
	public async Task<IActionResult> ProductDelete(ProductDTO productDTO)
	{
		ResponseDTO? response = await _productService.DeleteProductAsync(productDTO.ProductId);

		if (response != null && response.IsSuccess)
		{
			TempData["success"] = "Product Deleted Successful";
			return RedirectToAction(nameof(ProductIndex));
		}
		TempData["error"] = response?.Message;
		return View(productDTO);
	}
	
	public async Task<IActionResult> ProductEdit(int productId)
	{
		ResponseDTO? response = await _productService.GetAllProductsByIdAsync(productId);
		if (response != null && response.IsSuccess)
		{
			var model = JsonConvert.DeserializeObject<ProductDTO>(response.Result.ToString());
			return View(model);
		}
		TempData["error"] = response?.Message;
		return NotFound();
	}



	[HttpPost]
	public async Task<IActionResult> ProductEdit(ProductDTO productDTO)
	{

		if(ModelState.IsValid)
		{
            ResponseDTO? response = await _productService.UpdateProductAsync(productDTO);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Product Updated Successful";
                return RedirectToAction(nameof(ProductIndex));
            }
            TempData["error"] = response?.Message;
        }

        return View(productDTO);
		
	}
}

MadMicro.Web/Views/Shared/_Layout.cshtml
@using MadMicro.Web.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MadMicro.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MadMicro.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MadMicro.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.IsInRole(StaticDetail.RoleAdmin))
                        {
                            
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Product</a></li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Order" asp-action="OrderIndex">
                                Manage Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="ShopCart" asp-action="CartIndex">
                                &nbsp; <i class="bi bi-cart"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if(!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">🐻Hello   @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="text-center">
            MadTaddy@2023 Made Micro Services: MICRO EVE <i class="bi bi-unity"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MadMicro.Web/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}